Feature/password screen
V1taS/Random pull request #29
Opened 2022-08-05 12:33 UTC by tatyanaaaaaa

2022-08-05 19:06 UTC, V1taS requested changes

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +  private let charactersLabel = UILabel()
Лучше назвать **charactersCountLabel**

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +
Лишний отступ

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +extension PhrasePasswordView: UITextFieldDelegate {
Если ничего нет то фигурные скобки на одной линии {}

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +      let phrase = NSLocalizedString("Фраза", comment: "") + ":"
Не делаем форматирование в Аппирианс

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +      let getPassword = NSLocalizedString("Полученный пароль", comment: "") + ":"
Не делаем форматирование в Аппирианс

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Navigation/MainScreenCoordinator/PasswordScreenCoordinator/PasswordScreenCoordinator.swift
> +extension PasswordScreenCoordinator: PasswordScreenModuleOutput {
Если ничего нет то фигурные скобки на одной линии **{}**

2022-08-05 19:06 UTC, V1taS commented on Random/NewVersion/Navigation/MainScreenCoordinator/PasswordScreenCoordinator/PasswordScreenCoordinator.swift
> +
Лишний пробел

2022-08-08 08:37 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Interactor/PasswordScreenInteractor.swift
> +protocol PasswordScreenInteractorInput: AnyObject {
Готово

2022-08-08 08:38 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Interactor/PasswordScreenInteractor.swift
> +  private let rangeStartTextField = UITextField()
Готово

2022-08-08 08:38 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Interactor/PasswordScreenInteractor.swift
> +  private let rangeEndTextField = UITextField()
Готово

2022-08-08 08:38 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Interactor/PasswordScreenInteractor.swift
> +  private let resultLabel = UILabel()
Готово

2022-08-08 08:40 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +protocol PasswordScreenModuleInput: AnyObject {
Готово

2022-08-08 08:41 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +extension PhrasePasswordView: UITextFieldDelegate {
Готово

2022-08-08 08:42 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +    navigationBar()
Готово

2022-08-08 08:43 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +//    navigationItem.rightBarButtonItem = UIBarButtonItem(image: appearance.settingsButtonIcon,
готово

2022-08-08 08:43 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +  @objc private func cleanButtonAction() {
готово

2022-08-08 08:44 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +extension PasswordScreenViewController: PasswordScreenViewOutput {
готово

2022-08-08 08:46 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Factory/PasswordScreenFactory.swift
> +protocol PasswordScreenFactoryOutput: AnyObject {
готово

2022-08-08 09:25 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +  private let optionsLabel = UILabel()
готово

2022-08-08 09:25 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +extension PasswordScreenViewController: PasswordScreenInteractorOutput {
готово

2022-08-08 09:25 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Factory/PasswordScreenFactory.swift
> +
готово

2022-08-08 09:25 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Interactor/PasswordScreenInteractor.swift
> +protocol PasswordScreenInteractorOutput: AnyObject {
готово

2022-08-08 09:25 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Interactor/PasswordScreenInteractor.swift
> +  func getContent() {
готово

2022-08-08 09:26 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +protocol PasswordScreenModuleOutput: AnyObject {
готово

2022-08-08 09:26 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +
готово

2022-08-08 09:26 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Presenter/PasswordScreenModule.swift
> +extension PasswordScreenViewController: PasswordScreenFactoryOutput {
готово

2022-08-08 09:29 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +  private let labelsStackView = UIStackView()
готово

2022-08-08 09:32 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    uppercaseLettersSwitch.isOn = true
Эта строчка необходима, так как изначально свитч не активен

2022-08-08 09:32 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    lowercaseLettersSwitch.isOn = true
Эта строчка необходима, так как изначально свитч не активен

2022-08-08 09:32 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    symbolsSwitch.isOn = true
Эта строчка необходима, так как изначально свитч не активен

2022-08-08 09:35 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    generalStackView.distribution = .fill
готово

2022-08-08 09:35 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/Factory/PasswordScreenFactory.swift
> +protocol PasswordScreenFactoryInput: AnyObject {
готово

2022-08-08 09:36 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    numbersSwitch.isOn = true
Нет, свитч изначально выключен

2022-08-08 09:37 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +  @objc private func uppercaseSwitchValueDidChange(_ sender: UISwitch) {
готово

2022-08-08 09:37 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +  @objc private func lowercaseSwitchValueDidChange(_ sender: UISwitch) {
готово

2022-08-08 09:38 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +  @objc private func numbersSwitchValueDidChange(_ sender: UISwitch) {
готово

2022-08-08 09:38 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +  @objc private func symbolsSwitchValueDidChange(_ sender: UISwitch) {
готово

2022-08-08 09:38 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +extension PasswordGeneratorView: UITextFieldDelegate {
готово

2022-08-08 09:52 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    let parameters = NSLocalizedString("Параметры", comment: "") + ":"
готово

2022-08-08 09:52 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +    let longPassword = NSLocalizedString("Длина пароля", comment: "") + ":"
готово

2022-08-08 09:54 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +protocol PasswordScreenViewOutput: AnyObject {
готово

2022-08-08 09:54 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +protocol PasswordScreenViewInput: AnyObject {
готово

2022-08-08 09:56 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +                                           at: appearance.zero,
готово

2022-08-08 09:57 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +                                           at: appearance.first,
готово

2022-08-08 09:57 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +    if passwordSegmentedControl.selectedSegmentIndex == 0 {
готово

2022-08-08 09:59 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +    passwordSegmentedControl.selectedSegmentIndex = appearance.zero
Готово

2022-08-08 09:59 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +  @objc private func genarateButtonAction() {
Готово

2022-08-08 10:05 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +    let zero: Int = 0
готово

2022-08-08 10:05 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +    let first: Int = 1
готово

2022-08-08 10:08 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +    // MARK: - Private properties
Готово

2022-08-08 10:13 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +  private let layerView = UIView()
Готово

2022-08-08 10:14 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +  private let charactersLabel = UILabel()
Готово

2022-08-08 10:14 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +
Готово

2022-08-08 10:21 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +      let getPassword = NSLocalizedString("Полученный пароль", comment: "") + ":"
Готово

2022-08-08 10:21 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +      let phrase = NSLocalizedString("Фраза", comment: "") + ":"
Готово

2022-08-08 10:22 UTC, tatyanaaaaaa commented on Random/NewVersion/Navigation/MainScreenCoordinator/PasswordScreenCoordinator/PasswordScreenCoordinator.swift
> +
Готово

2022-08-08 10:22 UTC, tatyanaaaaaa commented on Random/NewVersion/Navigation/MainScreenCoordinator/PasswordScreenCoordinator/PasswordScreenCoordinator.swift
> +extension PasswordScreenCoordinator: PasswordScreenModuleOutput {
Готово

2022-08-08 10:49 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +      passwordLengthLabel.centerXAnchor.constraint(equalTo: centerXAnchor),
Этот лейбл - "Длина пароля", там не будет чисел. На айфон SE не растянулся

2022-08-08 10:58 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +    passwordSegmentedControl.addTarget(self, action: #selector(segmentedControlAction), for: .valueChanged)
Готово

2022-08-08 10:59 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordScreenView.swift
> +    let lessVerticalSpacing: CGFloat = 8
Готово

2022-08-08 11:14 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PhrasePasswordView.swift
> +      [phraseLabel, passwordLabel, resultLabel, layerView, phraseTextField, charactersLabel].forEach {
Готово

2022-08-08 11:15 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +      labelsStackView.widthAnchor.constraint(equalToConstant: appearance.widthAnchorSpacing),
Проверяла на iPhone SE - вся верстка в порядке

2022-08-08 11:15 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/PasswordScreenModule/View/PasswordGeneratorView.swift
> +      switcherStackView.widthAnchor.constraint(equalToConstant: appearance.widthAnchor),
Проверяла на iPhone SE - вся верстка в порядке

2022-08-09 18:09 UTC, V1taS approved these changes

2022-08-09 18:09 UTC, merged