Feature/cubes screen
V1taS/Random pull request #32
Opened 2022-08-15 16:06 UTC by tatyanaaaaaa

2022-08-15 16:21 UTC, V1taS requested changes

2022-08-15 16:21 UTC, V1taS commented on Random/NewVersion/Modules/CubesScreenModule/Presenter/CubesScreenModule.swift
> +
Лишний отступ

2022-08-15 16:21 UTC, V1taS commented on Random/NewVersion/Modules/CubesScreenModule/View/CubesScreenView.swift
> +
Лишний отступ

2022-08-24 09:29 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/CubesScreenModule/Presenter/CubesScreenModule.swift
> +
Готово

2022-08-24 09:29 UTC, tatyanaaaaaa commented on Random/NewVersion/Modules/CubesScreenModule/View/CubesScreenView.swift
> +
Готово

2022-08-24 15:01 UTC, closed without merging